const AV_PREFIX_LENGTH = 3;
const CYCLONE_DX_DOCUMENT_VERSION = 1;
const EMPTY_COUNT = 0;
const EXIT_FAILURE = 1;
const EXIT_SUCCESS = 0;
const FILE_TREE_EXECUTABLE_FLAG = 1;
const FILE_TREE_NON_EXECUTABLE_FLAG = 0;
const FIRST_CONTENT_INDEX = 1;
const HUMAN_LINE_NUMBER_OFFSET = 1;
const INCREMENT_STEP = 1;
const JSON_LD_CONTEXT_VERSION = 1.1;
const LAST_ITEM_OFFSET = -1;
const LISTING_ID_PAD_WIDTH = 3;
const MINIMAL_CARDINALITY = 1;
const PURL_SCOPE_PREFIX_LENGTH = 1;
const REQUIRED_CAPABILITY_BRIDGE_PAIR_COUNT = 2;
const REQUIRED_COMPONENT_COUNT = 1;
const REQUIRED_CONFORMANCE_REQUIREMENT_COUNT = 18;
const REQUIRED_VERSION_INDEX_ROWS = 2;
const SHA256_INTEGRITY_PREFIX_LENGTH = 7;
const TOML_ASSIGNMENT_MINIMUM_INDEX = 0;

const HTTP_ACCEPTED = 202;
const HTTP_BAD_REQUEST = 400;
const HTTP_UNAUTHORIZED = 401;
const HTTP_FORBIDDEN = 403;
const HTTP_NOT_FOUND = 404;
const HTTP_CONFLICT = 409;
const HTTP_GONE = 410;
const HTTP_PAYLOAD_TOO_LARGE = 413;
const HTTP_UNSUPPORTED_MEDIA_TYPE = 415;
const HTTP_TOO_MANY_REQUESTS = 429;

export {
  AV_PREFIX_LENGTH,
  CYCLONE_DX_DOCUMENT_VERSION,
  EMPTY_COUNT,
  EXIT_FAILURE,
  EXIT_SUCCESS,
  FILE_TREE_EXECUTABLE_FLAG,
  FILE_TREE_NON_EXECUTABLE_FLAG,
  FIRST_CONTENT_INDEX,
  HTTP_ACCEPTED,
  HTTP_BAD_REQUEST,
  HTTP_CONFLICT,
  HTTP_FORBIDDEN,
  HTTP_GONE,
  HTTP_NOT_FOUND,
  HTTP_PAYLOAD_TOO_LARGE,
  HTTP_TOO_MANY_REQUESTS,
  HTTP_UNAUTHORIZED,
  HTTP_UNSUPPORTED_MEDIA_TYPE,
  HUMAN_LINE_NUMBER_OFFSET,
  INCREMENT_STEP,
  JSON_LD_CONTEXT_VERSION,
  LAST_ITEM_OFFSET,
  LISTING_ID_PAD_WIDTH,
  MINIMAL_CARDINALITY,
  PURL_SCOPE_PREFIX_LENGTH,
  REQUIRED_CAPABILITY_BRIDGE_PAIR_COUNT,
  REQUIRED_COMPONENT_COUNT,
  REQUIRED_CONFORMANCE_REQUIREMENT_COUNT,
  REQUIRED_VERSION_INDEX_ROWS,
  SHA256_INTEGRITY_PREFIX_LENGTH,
  TOML_ASSIGNMENT_MINIMUM_INDEX,
};
