name: Dependency Review
on:
  pull_request:
permissions:
  contents: read
jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: write
    uses: agent-volumes/.github/.github/workflows/dependency-review-reusable.yml@main
